[package]
name = "jni-export"
version = "0.1.0"
edition = "2021"

[dependencies]
node-common = { path = "../node-common" }
state-manager = { path = "../state-manager" }
core-api-server = { path = "../core-api-server" }

jni = { workspace = true }

[lib]
name = "corerust"
crate_type = ["cdylib"]
