services:
  build-sm:
    environment:
      - TARGET=x86_64-unknown-linux-gnu
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../state-manager:/app
      - .cargo:/usr/local/cargo/registry