services:
  build-sm:
    environment:
      - TARGET=x86_64-unknown-linux-gnu
      - RUST_BINARY_TYPE=release
    build:
      context: .
      dockerfile: Dockerfile
      target: mapped-volume-build
    volumes:
      - ../../core-rust:/app
      - .cargo:/usr/local/cargo/registry