services:
  build-sm:
    environment:
      - TARGET=x86_64-unknown-linux-gnu
      - RUST_PROFILE=release
    build:
      context: .
      dockerfile: Dockerfile.local
      target: mapped-volume-build
    volumes:
      - ../../core-rust:/app # Allow caching incremental compilation artifacts
      - .cargo/registry:/usr/local/cargo/registry # Cache cargo downloads from the registry
      - .cargo/git:/usr/local/cargo/git # Cache cargo git checkouts
