[package]
name = "core-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
core-api-server = { path = "../core-api-server" }
state-manager = { path = "../state-manager" }

jni = { workspace = true }

[lib]
name = "corerust"
crate_type = ["cdylib"]
