openapi: 3.1.0
info:
  version: '0.1.0'
  title: 'Babylon Core API'
  license:
    name: The Radix License, Version 1.0
    url: https://www.radixfoundation.org/licenses/LICENSE-v1
servers:
  - url: 'localhost:3333/core'
tags:
  - name: Status
    x-displayName: Status Endpoints
    description: To query information about the Node / Ledger status.
  - name: Transaction
    x-displayName: Transaction Submission Endpoints
    description: To submit transactions to the network.
  - name: Mempool
    x-displayName: Mempool Endpoints
    description: To query mempool status.
  - name: Ledger State
    x-displayName: Ledger State Endpoints
    description: To query the current ledger state.
  - name: History Stream
    x-displayName: History Stream Endpoints
    description: To query the history of the ledger.
  - name: Key
    x-displayName: Key Endpoints
    description: To sign certain transactions with the node's own key.
paths:
  "/status/network-configuration":
    post:
      summary: Get Network Configuration
      description: Returns the network configuration of the network the node is connected to.
      tags:
        - Status
      responses:
        '200':
          description: Network Configuration
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/NetworkConfigurationResponse"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/transaction/submit":
    post:
      summary: Submit transaction to the network
      description: Returns whether the transaction submission was accepted.
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionSubmitRequest"
      responses:
        '200':
          description: Transaction Submit Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransactionSubmitResponse"
        '400':
          description: Client error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/transaction/preview":
    post:
      summary: Preview a transaction against the latest network state
      description: Returns the preview response
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TransactionPreviewRequest"
      responses:
        '200':
          description: Transaction preview response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TransactionPreviewResponse"
        '400':
          description: Client error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
  "/transactions":
    post:
      summary: Get committed transactions
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CommittedTransactionsRequest"
      responses:
        '200':
          description: Committed transactions response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CommittedTransactionsResponse"
        '400':
          description: Client error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
components:
  schemas:
###########################
# GENERAL / SHARED MODELS #
###########################
    TransactionStatus:
      type: string
      enum:
        - succeeded
        - failed
        - rejected
      description: The status of the transaction
    TransactionReceipt:
      type: object
      required:
        - status
        - fee_summary
      properties:
        status:
          "$ref": "#/components/schemas/TransactionStatus"
        fee_summary:
          "$ref": "#/components/schemas/FeeSummary"
        output:
          type: array
          items:
            type: string
        error_message:
          type: string
    NotarizedTransaction:
      type: object
      required:
        - hash
        - signed_intent
        - notary_signature
      properties:
        hash:
          type: string
        signed_intent:
          "$ref": "#/components/schemas/SignedTransactionIntent"
        notary_signature:
          type: string
    SignedTransactionIntent:
      type: object
      required:
        - hash
        - intent
        - intent_signatures
      properties:
        hash:
          type: string
        intent:
          "$ref": "#/components/schemas/TransactionIntent"
        intent_signatures:
          type: array
          items:
            "$ref": "#/components/schemas/IntentSignature"
    IntentSignature:
      type: object
      required:
        - public_key
        - signature
      properties:
        public_key:
          type: string
        signature:
          type: string
    TransactionIntent:
      type: object
      required:
        - hash
        - header
        - manifest
      properties:
        hash:
          type: string
        header:
          "$ref": "#/components/schemas/TransactionHeader"
        manifest:
          type: string
    TransactionHeader:
      type: object
      required:
        - version
        - network_id
        - start_epoch_inclusive
        - end_epoch_exclusive
        - nonce
        - notary_public_key
        - notary_as_signatory
        - cost_unit_limit
        - tip_percentage
      properties:
        version:
          type: integer
        network_id:
          type: integer
        start_epoch_inclusive:
          type: string
        end_epoch_exclusive:
          type: string
        nonce:
          type: string
        notary_public_key:
          type: string
        notary_as_signatory:
          type: boolean
        cost_unit_limit:
          type: string
        tip_percentage:
          type: string
    NetworkIdentifier:
      type: object
      required:
        - network
      properties:
        network:
          type: string
      example:
        network: mainnet
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          description: A numeric code corresponding to the given error type, roughly aligned with HTTP Status Code semantics (eg 400/404/500).
          type: integer
        message:
          description: A human-readable error message.
          type: string
        details:
          description: A structured/typed details object.
          $ref: "#/components/schemas/CoreErrorDetails"
        trace_id:
          description: A GUID to be used when reporting errors, to allow correlation with the Core API's error logs, in the case where the Core API details are hidden.
          type: string
    CoreErrorDetails:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          NetworkNotSupportedError: "#/components/schemas/NetworkNotSupportedError"
          InternalServerError: "#/components/schemas/InternalServerError"
          InvalidJsonError: "#/components/schemas/InvalidJsonError"
          InvalidHexError: "#/components/schemas/InvalidHexError"
          MempoolFullError: "#/components/schemas/MempoolFullError"
          InvalidTransactionError: "#/components/schemas/InvalidTransactionError"
          PreviewError: "#/components/schemas/PreviewError"
    NetworkNotSupportedError:
      allOf:
        - $ref: "#/components/schemas/CoreErrorDetails"
        - type: object
          required:
            - supported_networks
          properties:
            supported_networks:
              type: array
              items:
                $ref: "#/components/schemas/NetworkIdentifier"
    InternalServerError:
      allOf:
        - $ref: "#/components/schemas/CoreErrorDetails"
        - type: object
          properties:
            exception:
              type: string
            cause:
              type: string
    InvalidJsonError:
      allOf:
        - $ref: "#/components/schemas/CoreErrorDetails"
        - type: object
          properties:
            cause:
              type: string
    InvalidHexError:
      allOf:
        - $ref: "#/components/schemas/CoreErrorDetails"
        - type: object
          required:
            - invalid_hex
          properties:
            invalid_hex:
              type: string
    MempoolFullError:
      allOf:
        - $ref: "#/components/schemas/CoreErrorDetails"
        - type: object
          required:
            - mempool_transaction_count
          properties:
            mempool_transaction_count:
              type: integer
              format: int64
    InvalidTransactionError:
      allOf:
        - $ref: "#/components/schemas/CoreErrorDetails"
        - type: object
          required:
            - message
          properties:
            message:
              type: string
    PreviewError:
      allOf:
        - $ref: "#/components/schemas/CoreErrorDetails"
        - type: object
          required:
            - message
          properties:
            message:
              type: string
#########################################
# GENERAL / SHARED MODELS - Transaction #
#########################################
    FeeSummary:
      type: object
      required:
        - loan_fully_repaid
        - cost_unit_limit
        - cost_unit_consumed
        - cost_unit_price
        - tip_percentage
        - xrd_burned
        - xrd_tipped
      properties:
        loan_fully_repaid:
          type: boolean
        cost_unit_limit:
          type: string
        cost_unit_consumed:
          type: string
        cost_unit_price:
          type: string
        tip_percentage:
          type: string
        xrd_burned:
          type: string
        xrd_tipped:
          type: string
##########################################
# REQUEST: /status/network-configuration #
##########################################
    NetworkConfigurationResponse:
      type: object
      required:
        - version
        - network_identifier
        - network_hrp_suffix
      properties:
        version:
          description: Different versions regarding the node, network and api.
          type: object
          required:
            - core_version
            - api_version
          properties:
            core_version:
              type: string
            api_version:
              type: string
        network_identifier:
          "$ref": "#/components/schemas/NetworkIdentifier"
          description: The name of the network.
        network_hrp_suffix:
          type: string
          description: The network suffix used for bech32 hrps used for addressing.
################################
# REQUEST: /transaction/submit #
################################
    TransactionSubmitRequest:
      type: object
      required:
        - network_identifier
        - notarized_transaction
      properties:
        network_identifier:
          "$ref": "#/components/schemas/NetworkIdentifier"
          description: The name of the network.
        notarized_transaction:
          description: A notarized transaction encoded in the Radix transaction format, and then hex encoded.
          type: string
    TransactionSubmitResponse:
      type: object
      required:
        - duplicate
      properties:
        duplicate:
          description: Is true if the transaction is a duplicate of an existing transaction
            in the mempool.
          type: boolean
#################################
# REQUEST: /transaction/preview #
#################################
    TransactionPreviewRequest:
      type: object
      required:
        - network_identifier
        - manifest
        - cost_unit_limit
        - tip_percentage
        - nonce
        - signer_public_keys
        - flags
      properties:
        network_identifier:
          "$ref": "#/components/schemas/NetworkIdentifier"
          description: The name of the network.
        manifest:
          description: A transaction manifest. Sbor encoded, and then hex encoded.
          type: string
        cost_unit_limit:
          description: A limit of cost units available for execution
          type: string
        tip_percentage:
          description: A tip for the validator
          type: string
        nonce:
          description: A nonce value to use for execution
          type: string
        signer_public_keys:
          description: A list of public keys to be used as transaction signers, in a compressed format, hex encoded.
          type: array
          items:
            type: string
        flags:
          type: object
          required:
            - unlimited_loan
          properties:
            unlimited_loan:
              type: boolean
    TransactionPreviewResponse:
      type: object
      required:
        - transaction_status
        - transaction_fee
        - logs
        - new_package_addresses
        - new_component_addresses
        - new_resource_addresses
      properties:
        transaction_status:
          "$ref": "#/components/schemas/TransactionStatus"
        transaction_fee:
          "$ref": "#/components/schemas/FeeSummary"
          description: Fees to be paid
        logs:
          type: array
          items:
            type: object
            required:
              - level
              - message
            properties:
              level:
                type: string
              message:
                type: string
        new_package_addresses:
          description: A list of new package addresses
          type: array
          items:
            type: string
        new_component_addresses:
          description: A list of new component addresses
          type: array
          items:
            type: string
        new_resource_addresses:
          description: A list of new resource addresses
          type: array
          items:
            type: string
        output:
          type: array
          items:
            type: string
        error_message:
          type: string
##########################
# REQUEST: /transactions #
##########################
    CommittedTransactionsRequest:
      description: A request to retrieve a sublist of committed transactions from the
        ledger.
      type: object
      required:
        - network_identifier
        - state_version
        - limit
      properties:
        network_identifier:
          "$ref": "#/components/schemas/NetworkIdentifier"
          description: The name of the network
        state_version:
          type: string
        limit:
          description: The maximum number of transactions that will be returned.
          type: integer
    CommittedTransactionsResponse:
      type: object
      required:
        - state_version
        - transactions
      properties:
        state_version:
          type: string
        transactions:
          description: A committed transactions list starting from the `state_version`.
          type: array
          items:
            "$ref": "#/components/schemas/CommittedTransaction"
    CommittedTransaction:
      type: object
      required:
        - state_version
        - notarized_transaction
        - receipt
      properties:
        state_version:
          type: string
        notarized_transaction:
          "$ref": "#/components/schemas/NotarizedTransaction"
        receipt:
          "$ref": "#/components/schemas/TransactionReceipt"
