version: '3'
services:
  core0:
    environment:
      RADIXDLT_NETWORK_SEEDS_REMOTE: core0
      JAVA_OPTS: -server -Xms2g -Xmx2g -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50505,suspend=n,server=y
    build: .
    image: radixdlt.azurecr.io/radixdlt/radixdlt-core:emulator-1.0.0-beta
    networks:
      - single_node
    ports:
      - "8080:8080"
      - "9011:9011"
      - "50505:50505"
networks:
  single_node:
