version: '3'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core
      RADIXDLT_NETWORK_SEEDS_REMOTE: core
      RADIXDLT_CONSENSUS_FIXED_NODE_COUNT: 1
      RADIXDLT_LOG_LEVEL: debug
      RADIXDLT_UNIVERSE: ${RADIXDLT_UNIVERSE}
      JAVA_OPTS: -server -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:+AlwaysPreTouch -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStoreType=jks -Djava.security.egd=file:/dev/urandom -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.rmi.port=9011 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -agentlib:jdwp=transport=dt_socket,address=50505,suspend=n,server=y
    image: radixdlt/radixdlt-core:develop
    labels:
      com.radixdlt.roles: "core"
    networks:
      - single_node
    ports:
      - "8080:8080"
      - "9011:9011"
      - "9999:9999"
      - "50505:50505"
      - "10000:10000/tcp"
      - "20000:20000/tcp"
      - "30000:30000/tcp"
      - "10000:10000/udp"
      - "20000:20000/udp"
      - "30000:30000/udp"
    logging:
      options:
        max-size: "10m"
        max-file: "30"
  faucet:
    build:
      context: .
      dockerfile: Dockerfile.faucet
    environment:
      FAUCET_TOKEN_RRI: ${RADIXDLT_UNIVERSE_TOKEN}
      FAUCET_IDENTITY_KEY: ${RADIXDLT_UNIVERSE_PRIVKEY}
      RADIX_BOOTSTRAP_TRUSTED_NODE: http://core:8080
      JAVA_OPTS: -server -XX:+HeapDumpOnOutOfMemoryError -Xms512m -Xmx512m -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/urandom
    image: radixdlt/faucet:develop
    networks:
      - single_node
    ports:
      - "8079:8079"
    logging:
      options:
        max-size: "10m"
        max-file: "30"
networks:
  single_node:
