[workspace]
members = [
    "core-rust",
    "core-api-server",
    "state-manager",
]

[profile.dev]
opt-level = 3

# Recommended settings for wasmi for best performance
#  see: https://github.com/paritytech/wasmi/blob/master/CHANGELOG.md#0140---2022-07-26
[profile.release]
lto = "fat"
codegen-units = 1
