name: 'Build'
description: 'Build radixdlt and save artifacts. Uses github context'
inputs:
  is_release:
    description: 'True if it is a release'
    required: true
    default: false
  gradle_command:
    description: 'Gradle command to run'
    required: true
runs:
  using: "composite"
  steps:
    - id: setup_version_properties
      name: Setup version properties
      uses: ./.github/actions/setup-version-properties
    - id: set_variables
      run: |
        if [[ ${{ inputs.is_release }} == "false"  ]];then
          echo "Workflow triggered by push to a branch"
        fi
        version=${{ steps.setup_version_properties.outputs.VERSION_DISPLAY }}
        echo "Version: $version"
        ./gradlew ${{ inputs.gradle_command }}
      shell: bash
