name: 'Build'
description: 'Build radixdlt and save artifacts. Uses github context'
inputs:
  is_release:
    description: 'True if it is a release'
    required: true
    default: false
  gradle_command:
    description: 'Gradle command to run'
    required: true
runs:
  using: "composite"
  steps:
    - id: setup_version_properties
      name: Setup version properties
      uses: ./.github/actions/setup-version-properties
    - id: set_variables
      env:
        VERSION_BRANCH: ${{ steps.setup_version_properties.outputs.VERSION_BRANCH }}
        VERSION_COMMIT: ${{ steps.setup_version_properties.outputs.VERSION_COMMIT }}
        VERSION_DISPLAY: ${{ steps.setup_version_properties.outputs.VERSION_DISPLAY }}
        VERSION_BUILD: ${{ steps.setup_version_properties.outputs.VERSION_BUILD }}
        VERSION_TAG: ${{ steps.setup_version_properties.outputs.VERSION_TAG }}
        VERSION_LAST_TAG: ${{ steps.setup_version_properties.outputs.VERSION_LAST_TAG }}
      run: |
        if [[ ${{ inputs.is_release }} == "false"  ]];then
          echo "Workflow triggered by push to a branch"
        fi
        echo "Version: $VERSION_TAG"
        ./gradlew ${{ inputs.gradle_command }}
      shell: bash
