name: Build and Publish Keygen Image

on:
  workflow_dispatch:
    inputs:      
      image_tag:
        description: 'The tag for the keygen image'
        required: true
        type: string

jobs:

  dockerhub-keygen-docker:
    if: github.event_name == 'release'
    name: Build Keygen Image Dockerhub
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      environment: release
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "keygen"
      tag: ${{ github.event.release.tag_name }}
      context: "./docker"
      dockerfile: "./Dockerfile.keygen"
      platforms: "linux/amd64,linux/arm64"
      enable_dockerhub: "true"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  gcr-keygen-docker:
    if: github.event_name == 'workflow_dispatch'
    name: Build Keygen Image
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "eu.gcr.io"
      image_organization: "dev-container-repo"
      image_name: "keygen"
      tag: ${{ inputs.image_tag }}
      context: "./docker"
      dockerfile: "./Dockerfile.keygen"
      platforms: "linux/amd64,linux/arm64"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}