name: Build and Publish Keygen Image

on:
  workflow_dispatch:
    inputs:      
      image_tag:
        description: 'The tag for the keygen image'
        required: true
        type: string
  pull_request:
    paths:
      - 'cli-tools/src/**'

jobs:
  private-keygen-docker:
    if: github.event_name == 'workflow_dispatch'
    name: Dispatch - GCR
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "private-keygen"
      tag: ${{ inputs.image_tag }}
      context: "."
      dockerfile: "./Dockerfile"
      target: "keygen"
      platforms: "linux/amd64"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
  dockerhub-keygen-docker:
    if: github.event_name == 'workflow_dispatch'
    name: Dispatch - Dockerhub
    needs: gcr-keygen-docker
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      environment: release
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "keygen"
      tag: ${{ inputs.image_tag }}
      context: "."
      dockerfile: "./Dockerfile"
      target: "keygen"
      platforms: "linux/amd64"
      enable_dockerhub: "true"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

  private-keygen-docker-test:
    if: github.event_name == 'pull_request'
    name: PR
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "private-keygen"
      tags: |
        type=ref,event=branch
        type=ref,event=pr
      context: "."
      dockerfile: "./Dockerfile"
      target: "keygen"
      platforms: "linux/amd64"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}