name: Build and Publish Keygen Image

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'The tag for the keygen binary'
        required: true
        type: string
  pull_request:
    paths:
      - 'keygen/src/**'
  push:
    branches:
      - chore/release-key-gen

jobs:
  build-keygen-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: | 
        ./gradlew keygen:installDist
        ls -la
