name: Crosscompile

on: 
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    continue-on-error: true
    runs-on: '${{ matrix.os }}'
    timeout-minutes: 45
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: 'libcorerust.dylib'
            zipname: 'arch-darwin-x86_64'
            custom-linker: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: 'libcorerust.dylib'
            zipname: 'arch-darwin-aarch64'
            custom-linker: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: 'libcorerust.so'
            zipname: 'arch-linux-x86_64'
            custom-linker: ""
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            zipname: 'arch-linux-aarch64'
            artifact: 'libcorerust.so'
            custom-linker: "aarch64-linux-gnu-gcc"
          # - os: ubuntu-latest
          #   target: i686-unknown-linux-gnu
          #   zipname: 'arch-linux-i686'
          #   artifact: 'libcorerust.so'
          #   custom-linker: "i686-linux-gnu-gcc"
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: 'corerust.dll'
            zipname: 'arch-windows-x86_64-msvc'
            custom-linker: ""
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            artifact: 'corerust.dll'
            zipname: 'arch-windows-x86_64-gnu'
            custom-linker: ""
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: '${{ runner.os }}-${{ matrix.target }}-cargo-registry-${{ hashFiles(''**/Cargo.lock'') }}'
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: '${{ runner.os }}-${{ matrix.target }}-cargo-index-${{ hashFiles(''**/Cargo.lock'') }}'
      - uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Rust Targets
        run: |
          rustup target install ${{ matrix.target }}
      - if: matrix.os == 'windows-latest'
        name: Build dependencies windows
        run: |
          rustup toolchain install stable-gnu
          rustup set default-host ${{ matrix.target }}
      - if: matrix.os == 'ubuntu-latest'
        name: Build dependencies ubuntu
        run: |
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          # sudo apt install -y gcc-i686-linux-gnu g++-i686-linux-gnu
      - name: Build core-rust
        run: |
          export LINKER_ENVIRONMENT_VARIABLE="CARGO_TARGET_"$(echo ${{ matrix.target }} | tr '[:lower:]' '[:upper:]' | sed 's/-/_/g')"_LINKER"
          if [ ! -z "${{ matrix.custom-linker }}" ]
          then
            export $LINKER_ENVIRONMENT_VARIABLE=${{ matrix.custom-linker }}
          fi

          cd core-rust
          cargo build --release --profile=release --target ${{ matrix.target }}
          pwd
          echo "ls  ./target/"
          ls  ./target/
          echo "ls  ./target/release"
          ls  ./target/release/
          echo "ls  ./target/${{ matrix.target }}/release"
          ls  ./target/${{ matrix.target }}/release/
      - uses: actions/upload-artifact@master
        with:
          name: libcorerust-${{ matrix.target }}
          path: ./core-rust/target/${{ matrix.target }}/release/${{ matrix.artifact }}
          if-no-files-found: error
      
      
  release:
    if: github.event_name == 'release'
    needs: 
      - build
    runs-on: 'ubuntu-latest'
    continue-on-error: true
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            artifact: 'libcorerust.dylib'
            zipname: 'arch-darwin-x86_64'
          - target: aarch64-apple-darwin
            artifact: 'libcorerust.dylib'
            zipname: 'arch-darwin-aarch64'
          - target: x86_64-unknown-linux-gnu
            artifact: 'libcorerust.so'
            zipname: 'arch-linux-x86_64'
          - target: aarch64-unknown-linux-gnu
            artifact: 'libcorerust.so'
            zipname: 'arch-linux-aarch64'
          # - target: i686-unknown-linux-gnu
          #   artifact: 'libcorerust.so'
          #   zipname: 'arch-linux-i686'
          - target: x86_64-pc-windows-msvc
            artifact: 'corerust.dll'
            zipname: 'arch-windows-x86_64-msvc'
          - target: x86_64-pc-windows-gnu
            artifact: 'corerust.dll'
            zipname: 'arch-windows-x86_64-gnu'
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - uses: actions/download-artifact@v3
        with:
          name: libcorerust-${{ matrix.target }}
          path: libcorerust-${{ matrix.target }}
      - name: Build core-rust
        run: |
          ls -lah
          ls -lah libcorerust-${{ matrix.target }}
          zip -j babylon-node-rust-${{ matrix.zipname }}-release-${{ github.event.release.tag_name }}.zip libcorerust-${{ matrix.target }}/${{ matrix.artifact }}
          ls -lah
      - if: github.event_name == 'release'
        name: Get release
        id: get_release
        uses: bruceadams/get-release@74c3d60f5a28f358ccf241a00c9021ea16f0569f
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - if: github.event_name == 'release'
        id: get_version
        name: Get radixdlt version
        uses: ./.github/actions/get-version
        with:
          is_release: true
      - if: github.event_name == 'release'
        name: Upload distribution zip
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: babylon-node-rust-${{ matrix.zipname }}-release-${{ github.event.release.tag_name }}.zip
          asset_name: babylon-node-rust-${{ matrix.zipname }}-release-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip