name: Docker

on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - develop
      - main
      - release\/*

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-22.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  build_deb:
    name: Build debian package
    runs-on: babylon-runner
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            eu.gcr.io/dev-container-repo/babylon-node
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          flavor: |
            latest=false
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-deb
          restore-keys: ${{ runner.os }}-gradle-deb
      - id: auth
        uses: google-github-actions/auth@a61909d048e0be579b6c15b27088d19668493851
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce'
      - name: 'Register gcloud as Docker credential helper'
        run: |
          gcloud auth configure-docker -q
      - name: Create deb package
        run: |
          sudo apt-get update && sudo apt-get install make
          cd core && make build-core
      - name: Upload generated debian package
        uses: actions/upload-artifact@v3.1.0
        with:
          name: deb4docker
          path: "${{ github.workspace }}/docker/*.deb"

  build_push_container:
    name: (GCR) Docker
    needs: build_deb
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest
      image_registry: "eu.gcr.io"
      image_organization: "dev-container-repo"
      image_name: "babylon-node"
      tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=sha
      context: "docker"
      dockerfile: "./docker/Dockerfile.core"
      platforms: "linux/amd64,linux/arm64"
      restore_artifacts: "true"
      artifact_name: "deb4docker"
      artifact_location: "docker"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  build_push_container_dockerhub:
    name: (DockerHub) Docker
    needs: build_deb
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      environment: release
      runs_on: ubuntu-latest
      image_registry: "registry.hub.docker.com"
      image_organization: "radixdlt"
      image_name: "babylon-node"
      tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=sha
      context: "docker"
      dockerfile: "./docker/Dockerfile.core"
      platforms: "linux/amd64,linux/arm64"
      restore_artifacts: "true"
      artifact_name: "deb4docker"
      artifact_location: "docker"
      enable_dockerhub: "true"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

# TEMPORARILY REMOVE EPHEMERAL TESTS
# => Until we can change them to only run the "node" tests and not the transaction tests
# ephemeral-deploy-and-test:
#   name: Run ephemeral deploy and test
#   needs:
#     - build_deb
#     - build_push_container
#   runs-on: ubuntu-22.04
#   steps:
#     - name: Get docker image tag
#       run: |
#         #There can be multiple tag entries. Get the first and only take the tag (i.e. not the image repo and name)
#         TAGS="${{ needs.build_deb.outputs.tags }}"
#         DOCKER_TAG=$(echo $TAGS | awk 'NR==1{print $1}' | cut -d':' -f2)
#         echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
#         echo "BABYLON_NODE_BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV
#     - name: Deploy and test on ephemeral network
#       uses: toptal/jenkins-job-trigger-action@1.0.0
#       with:
#         jenkins_url: "${{ secrets.JENKINS_URL }}"
#         jenkins_user: ${{ secrets.JENKINS_USER }}
#         jenkins_token: ${{ secrets.BABYLON_NODE_JENKINS_API_TOKEN }}
#         job_name: "ephemeral-deployments/job/ephemeral-env-deploy-and-test"
#         job_params: |
#           {
#             "nodeDockerTag": "${{ env.DOCKER_TAG }}",
#             "babylonNodeBranch": "${{ env.BABYLON_NODE_BRANCH }}"
#           }
#         job_timeout: "3600"
