name: Somestuff

on: push

jobs:
  build_push_container:
    uses: radixdlt/babylon-node/.github/workflows/docker-build.yml@DO-1214/docker-build-action
    with:
      environment: ""
      # image information
      image_registry: "eu.gcr.io"
      image_organization: "dev-container-repo"
      image_name: "babylon-node"
      tag: "DO-1214"
      labels: ""
      # build information
      restore_artifact: "true"
      artifact_name: "deb4docker"
      artifact_location: "docker"
      context: "docker"
      dockerfile: "./docker/Dockerfile.core"
      platforms: "linux/amd64"
      # optimizations
      cache_repo: "eu.gcr.io/dev-container-repo/babylon-node"
      cache_tag_suffix: "pr"
      # role_to_assume: "arn:aws:iam::308190735829:role/gh-dockerhub-releaser"
  