name: Docker

on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - develop
      - main
      - release\/*

jobs:
  
  oidc-access-test:
    if: github.event_name == 'release'
    name: OIDC access test
    runs-on: ubuntu-latest
    environment: release2
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@516dbb0c760f39b4cdd750ae095f1688780f68f4
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355
        with:
          role-to-assume: arn:aws:iam::308190735829:role/gh-common-secrets-read-access
          aws-region: eu-west-2
      # This is version v1.0.4
      # https://github.com/aws-actions/configure-aws-credentials/releases/tag/v1.0.4
      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: aws-actions/aws-secretsmanager-get-secrets@022e8919774ecb75e8e375656d7b1898936ab878
        with:
          secret-ids: |
            DOCKERHUB_PRIVATE, github-actions/common/dockerhub-credentials
          parse-json-secrets: true
      - name: OIDC access test
        run: |
          echo ${{ secrets.DOCKERHUB_RELEASER_ROLE }}
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}
          aws-region: eu-west-2
      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: aws-actions/aws-secretsmanager-get-secrets@022e8919774ecb75e8e375656d7b1898936ab878
        with:
          secret-ids: |
            DOCKERHUB_PUBLIC, github-actions/rdxworks/dockerhub-images/release-credentials
          parse-json-secrets: true
      - name: OIDC access test
        run: |
          echo ${{ secrets.DOCKERHUB_PUBLIC_USERNAME }}
      
