name: Test Secret Access

on:
  pull_request:

jobs:
  test:
    name: Test Secret Access
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/fetch-secrets
        with: 
          role_name: "arn:aws:iam::308190735829:role/gh-babylon-node-secrets-read-access"
          app_name: "babylon-node"
          step_name: "deploy"
          secret_prefix: "JENKINS_API_"
          secret_name: "github-actions/radixdlt/babylon-node/jenkins-api-token"
          parse_json: true
      - uses: ./.github/actions/fetch-secrets
        with: 
          role_name: "arn:aws:iam::308190735829:role/gh-babylon-node-secrets-read-access"
          app_name: "babylon-node"
          step_name: "publish-core-sdk-npmjs"
          secret_prefix: "NODE_AUTH_"
          secret_name: "github-actions/radixdlt/babylon-node/npm-publishing-secret"
          parse_json: true